GET http://localhost:8080/places?text=av visconde rio branco, 3556

###
GET http://localhost:8080/places?text=av amazonas, belo horizonte, 1000

###
 ChIJMyzPysqQpgARlznSOl55NVs
@originId = ChIJp2Gnxd1IxwcROukAhSHZ8_c
@destinationId = ChIJPUqddeKZpgARusD9CDpIBDQ

###
GET http://localhost:8080/directions?originId={{ originId }}&destinationId={{ destinationId }}

###
POST http://localhost:8080/routes
Content-Type: application/json

{
    "name": "rota 1",
    "source_id": "{{ originId }}",
    "destination_id": "{{ destinationId }}"
}

###
GET http://localhost:8080/routes

###
GET http://localhost:8080/routes/674ef78bab1148ea9161c23b